### PR TITLE
New command : get_squares_between

### PR DESCRIPTION
**Pull request by BastienDuplessier**
## Changes
- Add new command `get_squares_between(xa, ya, xb, yb)` which returns an array of all squares touched by the segment AB.

Example :
faim
Red : Horizontal / Vertiacal
Blue : Diagonal
Green : Other

I'm currently writing a chess system which will use this. It will allow to check if everything is alright.

## Todo
- [x] Add : `get_squares_between_events(id1, id2)`
- [x] Move implementation into Point class
- [x] Chess system
- [x] Common event examples

### CODE REVIEW

**Comment by BastienDuplessier** [comment]
@xvw Good idea !
@grrim I was a bit bothered by the length of the method and the fact it was in `Command.rb`. You make a good point, I'll follow your advice :)

**Comment by acs-l** [comment]
**I'm not very fond of the *command's name*** (`get_squares_between`) 😕.

Firstly, because there is **already an existing command with quite the same name**: [`squares_between`](https://github.com/RMEx/RME/blob/master/src/Commands.rb#L1989). 
*'Though it might be the latter one which is misnamed as it returns the number of squares between two events*...

In the other hand, I do think that **speaking about `squares` instead of `tiles` is a wrong idea**. 
*In RPG Maker's manual and in many tutorials, the unit which divides the map's grid is referred as tiles, not squares*. (*Unfortunately, many other commands are using `squares` for `tiles` in their name* 😞)

Finally, **`get` is quite an all-purpose prefix**.
*It doesn't explicitly evoke the fact of enumerating a collection of tiles*.

---

Therefore, I'd rather use something like: `list_tiles_between` (*or: `as_a_ghost_list_tiles_between` as this command does not factor obstacles* ^^')

**Comment by BastienDuplessier** [comment]
I've based the name of this new command on the already existing commands name.
There's already some commands which returns that kind of results, I've based this name on theses commands : 
- http://rmex.github.io/RMEDoc/#get_squares_by_tile
- http://rmex.github.io/RMEDoc/#get_squares_by_region
- http://rmex.github.io/RMEDoc/#get_squares_by_terrain

I don't like the word `tile``because it's more the graphical element (which might be a tile_id) than XY coordinates.

`get_squares_between` is not a name I really like but it's consistent with other commands.

**Comment by acs-l** [comment]
Well... Even though I'm not entirely convinced by this "*consistency*" argument because there hasn't ever been any naming convention regarding commands, I do hear and understand your point.
**Therefore, no changes for current versions.**

---

**However, I have to admit that my question was more global and related to the next major release of [`RMEx/RME`](https://github.com/RMEx/RME) (namely: `2.0.0` ?).** As I am currently refactoring the whole commands' declaration, I am listing quite a few *discrepancies* and *inconsistencies*. Thus, I was wondering if we should not consider a pair-reading of all the available commands and stating for each of them, if their name is whether relevant or not. Leading us to choose if we might change one command's name or not.
I'd like to have your opinion (@xvw, @BastienDuplessier, @grrim and @Jauke) on this matter. Firstly to see if we are on the same page regarding this, and secondly to see if we could not involve some of RME's user regarding commands' naming. (*I might as well create a whole new issue to adress this point, instead of polluting this pull request*. Sorry Bastien 😅 !)

From my point of view, this change of names can be performed in a really easy and smooth way for the next major release. For instance: *I can add a warning pop-up redirecting to the new command's name, each times the usage of an old command is detected* !

**Comment by BastienDuplessier** [comment]
I've updated the code. If you have time, I'd like you to do another review please @xvw @grrim .
I'm not quite satisfied with the code right now, but I don't know what to do to improve it.

**Pull request merged**
